#!/bin/sh
MNT_POINT=${1}
ROOT_MOUNT=$(awk '$2=="/" {print substr($4,1,2)}' < /etc/fstab)
if [ ${ROOT_MOUNT} = "rw" ]; then
	/bin/mount --bind ${MNT_POINT}_orig ${MNT_POINT}
else
	/bin/mount -t tmpfs ramdisk ${MNT_POINT}_rw
	/usr/bin/unionfs-fuse -o cow,allow_other,suid,dev,nonempty ${MNT_POINT}_rw=RW:${MNT_POINT}_orig=RO ${MNT_POINT}
fi
